modmap:
  - name: All applications
    remap:
      CapsLock: Esc
      Esc: CapsLock
    # CapsLock:
    #   skip_key_event: true
    #   held: Esc # Required, also accepts arrays
    #   alone: Esc # Required, also accepts arrays
    #   alone_timeout_millis: 1000 # Optional
keymap:
  # - name: All applications except Alacritty
  #   application:
  #     not: [Alacritty, Cursor]
  #   remap:
  #     Alt-c: C-c
  #     Alt-v: C-v
  #     C-c: Alt-c
  #     C-v: Alt-v
  #
  - name: Alacritty 
    application:
      only: [Alacritty, Cursor]
    remap:
      # C-c: C-Shift-c
      # C-v: C-Shift-v
      Alt-LEFTBRACE: Alt-LEFT
      Alt-RIGHTBRACE: Alt-RIGHT

  # - name: Cursor 
  #   application:
  #     only: Cursor
  #   remap:
  #     CapsLock: Esc
  #     Esc: CapsLock

  - name: All applications
    remap:
      LEFTMETA-s: C-Shift-tab
      LEFTMETA-d: C-tab
      Alt-a: C-a
      Alt-d: C-d
